version: '3'
services:
  redis:
    container_name: cache
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    expose: [6379]
    environment:
      - REDIS_URL=redis://cache
  flask-gateway:
    image: flask-gateway:latest
    container_name: gateway
    ports:
      - 5000:5000
    expose: [5000]
    depends_on:
      - redis
  db-mongo:
    image: mongo:latest
    container_name: db-mongo
    environment:
      - MONGO_INITDB_DATABASE=service2-mongo-students
    ports:
      - 27018:27018
    command: mongod --port 27018
    expose:
      - 27018
  service-sanic2:
    image: service-sanic2:latest
    container_name: service-s2
    ports:
      - 8000:8000
    expose: [8000]
    links:
      - db-mongo
    