version: '2'
services:
  redis:
    container_name: cache
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    expose: [6379]
    environment:
      - REDIS_URL=redis://cache
  flask-gateway:
    image: flask-gateway:latest
    container_name: gateway
    ports:
      - 5000:5000
    expose: [5000]
  